
//水浒人物列表

var character = new Array();
var profile = new Array();
var sexflag = new Array();

var i = 1;
for(i = 1; i <= 108; i++)  { character[i] = ''; profile[i] = '';sexflag[i] = 1;}

//三十六天罡星
character[1] = '　　天魁星 &nbsp;&nbsp;&nbsp;&nbsp;呼保义 &nbsp;&nbsp;&nbsp;&nbsp;宋　江';
character[2] = '　　天罡星 &nbsp;&nbsp;&nbsp;&nbsp;玉麒麟 &nbsp;&nbsp;&nbsp;&nbsp;卢俊义';
character[3] = '　　天机星 &nbsp;&nbsp;&nbsp;&nbsp;智多星 &nbsp;&nbsp;&nbsp;&nbsp;吴　用';
character[4] = '　　天闲星 &nbsp;&nbsp;&nbsp;&nbsp;入云龙 &nbsp;&nbsp;&nbsp;&nbsp;公孙胜';
character[5] = '　　天勇星 &nbsp;&nbsp;&nbsp;&nbsp;大　刀 &nbsp;&nbsp;&nbsp;&nbsp;关　胜';
character[6] = '　　天雄星 &nbsp;&nbsp;&nbsp;&nbsp;豹子头 &nbsp;&nbsp;&nbsp;&nbsp;林　冲';
character[7] = '　　天猛星 &nbsp;&nbsp;&nbsp;&nbsp;霹雳火 &nbsp;&nbsp;&nbsp;&nbsp;秦　明';
character[8] = '　　天威星 &nbsp;&nbsp;&nbsp;&nbsp;双　鞭 &nbsp;&nbsp;&nbsp;&nbsp;呼延灼';
character[9] = '　　天英星 &nbsp;&nbsp;&nbsp;&nbsp;小李广 &nbsp;&nbsp;&nbsp;&nbsp;花　荣';
character[10] = '　  天贵星 &nbsp;&nbsp;&nbsp;&nbsp;小旋风 &nbsp;&nbsp;&nbsp;&nbsp;柴　进';
character[11] = '　  天富星 &nbsp;&nbsp;&nbsp;&nbsp;扑天雕 &nbsp;&nbsp;&nbsp;&nbsp;李　应';
character[12] = '　  天满星 &nbsp;&nbsp;&nbsp;&nbsp;美髯公 &nbsp;&nbsp;&nbsp;&nbsp;朱　仝';
character[13] = '　　天孤星 &nbsp;&nbsp;&nbsp;&nbsp;花和尚 &nbsp;&nbsp;&nbsp;&nbsp;鲁智深';
character[14] = '　　天伤星 &nbsp;&nbsp;&nbsp;&nbsp;行　者 &nbsp;&nbsp;&nbsp;&nbsp;武　松';
character[15] = '　　天立星 &nbsp;&nbsp;&nbsp;&nbsp;双枪将 &nbsp;&nbsp;&nbsp;&nbsp;董　平';
character[16] = '　　天捷星 &nbsp;&nbsp;&nbsp;&nbsp;没羽箭 &nbsp;&nbsp;&nbsp;&nbsp;张　清';
character[17] = '　　天暗星 &nbsp;&nbsp;&nbsp;&nbsp;青面兽 &nbsp;&nbsp;&nbsp;&nbsp;杨　志';
character[18] = '　　天佑星 &nbsp;&nbsp;&nbsp;&nbsp;金枪手 &nbsp;&nbsp;&nbsp;&nbsp;徐　宁';
character[19] = '　　天空星 &nbsp;&nbsp;&nbsp;&nbsp;急先锋 &nbsp;&nbsp;&nbsp;&nbsp;索　超';
character[20] = '　　天速星 &nbsp;&nbsp;&nbsp;&nbsp;神行太保 &nbsp;&nbsp;&nbsp;&nbsp;戴　宗';
character[21] = '　　天异星 &nbsp;&nbsp;&nbsp;&nbsp;赤发鬼 &nbsp;&nbsp;&nbsp;&nbsp;刘　唐';
character[22] = '　　天杀星 &nbsp;&nbsp;&nbsp;&nbsp;黑旋风 &nbsp;&nbsp;&nbsp;&nbsp;李　逵';
character[23] = '　　天微星 &nbsp;&nbsp;&nbsp;&nbsp;九纹龙 &nbsp;&nbsp;&nbsp;&nbsp;史　进';
character[24] = '　　天究星 &nbsp;&nbsp;&nbsp;&nbsp;没遮拦 &nbsp;&nbsp;&nbsp;&nbsp;穆　弘';
character[25] = '　　天退星 &nbsp;&nbsp;&nbsp;&nbsp;插翅虎 &nbsp;&nbsp;&nbsp;&nbsp;雷　横';
character[26] = '　　天寿星 &nbsp;&nbsp;&nbsp;&nbsp;混江龙 &nbsp;&nbsp;&nbsp;&nbsp;李　俊';
character[27] = '　　天剑星 &nbsp;&nbsp;&nbsp;&nbsp;立地太岁&nbsp;&nbsp;&nbsp;&nbsp;阮小二';
character[28] = '　　天竟星 &nbsp;&nbsp;&nbsp;&nbsp;船火儿 &nbsp;&nbsp;&nbsp;&nbsp;张　横';
character[29] = '　　天罪星 &nbsp;&nbsp;&nbsp;&nbsp;短命二郎 &nbsp;&nbsp;&nbsp;&nbsp;阮小五';
character[30] = '    天损星 &nbsp;&nbsp;&nbsp;&nbsp;浪里白条 &nbsp;&nbsp;&nbsp;&nbsp;张  顺';
character[31] = '　　天败星 &nbsp;&nbsp;&nbsp;&nbsp;活阎罗 &nbsp;&nbsp;&nbsp;&nbsp;阮小七';
character[32] = '　　天牢星 &nbsp;&nbsp;&nbsp;&nbsp;病关索 &nbsp;&nbsp;&nbsp;&nbsp;杨　雄';
character[33] = '　　天慧星 &nbsp;&nbsp;&nbsp;&nbsp;拚命三郎 &nbsp;&nbsp;&nbsp;&nbsp;石　秀';
character[34] = '　　天暴星 &nbsp;&nbsp;&nbsp;&nbsp;两头蛇 &nbsp;&nbsp;&nbsp;&nbsp;解　珍';
character[35] = '　　天哭星 &nbsp;&nbsp;&nbsp;&nbsp;双尾蝎 &nbsp;&nbsp;&nbsp;&nbsp;解　宝';
character[36] = '　　天巧星 &nbsp;&nbsp;&nbsp;&nbsp;浪　子 &nbsp;&nbsp;&nbsp;&nbsp;燕　青';

//七十二地煞星　

character[37] = '　　地魁星 &nbsp;&nbsp;&nbsp;&nbsp;神机军师 &nbsp;&nbsp;&nbsp;&nbsp;朱　武';
character[38] = '　　地煞星 &nbsp;&nbsp;&nbsp;&nbsp;镇三山 &nbsp;&nbsp;&nbsp;&nbsp;黄　信';
character[39] = '　　地勇星 &nbsp;&nbsp;&nbsp;&nbsp;病尉迟 &nbsp;&nbsp;&nbsp;&nbsp;孙　立';
character[40] = '　　地杰星 &nbsp;&nbsp;&nbsp;&nbsp;丑郡马 &nbsp;&nbsp;&nbsp;&nbsp;宣　赞';
character[41] = '　　地雄星 &nbsp;&nbsp;&nbsp;&nbsp;井木犴 &nbsp;&nbsp;&nbsp;&nbsp;郝思文';
character[42] = '　　地威星 &nbsp;&nbsp;&nbsp;&nbsp;百胜将 &nbsp;&nbsp;&nbsp;&nbsp;韩　滔';
character[43] = '　　地英星 &nbsp;&nbsp;&nbsp;&nbsp;天目将 &nbsp;&nbsp;&nbsp;&nbsp;彭  圯 ';
character[44] = '　　地奇星 &nbsp;&nbsp;&nbsp;&nbsp;圣水将 &nbsp;&nbsp;&nbsp;&nbsp;单　廷';
character[45] = '　　地猛星 &nbsp;&nbsp;&nbsp;&nbsp;神火将 &nbsp;&nbsp;&nbsp;&nbsp;魏定国';
character[46] = '　　地文星 &nbsp;&nbsp;&nbsp;&nbsp;圣手书生 &nbsp;&nbsp;&nbsp;&nbsp;萧　让';
character[47] = '　　地正星 &nbsp;&nbsp;&nbsp;&nbsp;铁面孔目 &nbsp;&nbsp;&nbsp;&nbsp;裴　宣';
character[48] = '　　地阔星 &nbsp;&nbsp;&nbsp;&nbsp;摩云金翅 &nbsp;&nbsp;&nbsp;&nbsp;欧　鹏';
character[49] = '　　地阖星 &nbsp;&nbsp;&nbsp;&nbsp;火眼狻猊 &nbsp;&nbsp;&nbsp;&nbsp;邓　飞';
character[50] = '　  地强星 &nbsp;&nbsp;&nbsp;&nbsp;锦毛虎 &nbsp;&nbsp;&nbsp;&nbsp;燕　顺';
character[51] = '　　地暗星 &nbsp;&nbsp;&nbsp;&nbsp;锦豹子 &nbsp;&nbsp;&nbsp;&nbsp;杨　林';
character[52] = '　　地轴星 &nbsp;&nbsp;&nbsp;&nbsp;轰天雷 &nbsp;&nbsp;&nbsp;&nbsp;凌　振';
character[53] = '　　地会星 &nbsp;&nbsp;&nbsp;&nbsp;神算子 &nbsp;&nbsp;&nbsp;&nbsp;蒋　敬';
character[54] = '　　地佐星 &nbsp;&nbsp;&nbsp;&nbsp;小温侯 &nbsp;&nbsp;&nbsp;&nbsp;吕　方';
character[55] = '　　地佑星 &nbsp;&nbsp;&nbsp;&nbsp;赛仁贵 &nbsp;&nbsp;&nbsp;&nbsp;郭　盛';
character[56] = '　　地灵星 &nbsp;&nbsp;&nbsp;&nbsp;神　医 &nbsp;&nbsp;&nbsp;&nbsp;安道全';
character[57] = '　　地兽星 &nbsp;&nbsp;&nbsp;&nbsp;紫髯伯 &nbsp;&nbsp;&nbsp;&nbsp;皇甫端';
character[58] = '　　地微星 &nbsp;&nbsp;&nbsp;&nbsp;矮脚虎 &nbsp;&nbsp;&nbsp;&nbsp;王　英';
character[59] = '　　地慧星 &nbsp;&nbsp;&nbsp;&nbsp;一丈青 &nbsp;&nbsp;&nbsp;&nbsp;扈三娘';sexflag[59] = 0;
character[60] = '　　地暴星 &nbsp;&nbsp;&nbsp;&nbsp;丧门神 &nbsp;&nbsp;&nbsp;&nbsp;鲍　旭';
character[61] = '　　地然星 &nbsp;&nbsp;&nbsp;&nbsp;混世魔王 &nbsp;&nbsp;&nbsp;&nbsp;樊　瑞';
character[62] = '　　地猖星 &nbsp;&nbsp;&nbsp;&nbsp;毛头星 &nbsp;&nbsp;&nbsp;&nbsp;孔　明';
character[63] = '　　地狂星 &nbsp;&nbsp;&nbsp;&nbsp;独火星 &nbsp;&nbsp;&nbsp;&nbsp;孔　亮';
character[64] = '　　地飞星 &nbsp;&nbsp;&nbsp;&nbsp;八臂哪吒 &nbsp;&nbsp;&nbsp;&nbsp;项　充';
character[65] = '　　地走星 &nbsp;&nbsp;&nbsp;&nbsp;飞天大圣 &nbsp;&nbsp;&nbsp;&nbsp;李　衮';
character[66] = '　　地巧星 &nbsp;&nbsp;&nbsp;&nbsp;玉臂匠 &nbsp;&nbsp;&nbsp;&nbsp;金大坚';
character[67] = '　　地明星 &nbsp;&nbsp;&nbsp;&nbsp;铁笛仙 &nbsp;&nbsp;&nbsp;&nbsp;马　麟';
character[68] = '　　地进星 &nbsp;&nbsp;&nbsp;&nbsp;出洞蛟 &nbsp;&nbsp;&nbsp;&nbsp;童　威';
character[69] = '　　地退星 &nbsp;&nbsp;&nbsp;&nbsp;翻江蜃 &nbsp;&nbsp;&nbsp;&nbsp;童　猛';
character[70] = '　　地满星 &nbsp;&nbsp;&nbsp;&nbsp;玉幡竿 &nbsp;&nbsp;&nbsp;&nbsp;孟　康';
character[71] = '　　地遂星 &nbsp;&nbsp;&nbsp;&nbsp;通臂猿 &nbsp;&nbsp;&nbsp;&nbsp;侯　健';
character[72] = '　　地周星 &nbsp;&nbsp;&nbsp;&nbsp;跳涧虎 &nbsp;&nbsp;&nbsp;&nbsp;陈　达';
character[73] = '　　地隐星 &nbsp;&nbsp;&nbsp;&nbsp;白花蛇 &nbsp;&nbsp;&nbsp;&nbsp;杨　春';
character[74] = '　　地异星 &nbsp;&nbsp;&nbsp;&nbsp;白面郎君 &nbsp;&nbsp;&nbsp;&nbsp;郑天寿';
character[75] = '　　地理星 &nbsp;&nbsp;&nbsp;&nbsp;九尾龟 &nbsp;&nbsp;&nbsp;&nbsp;陶宗旺';
character[76] = '　　地俊星 &nbsp;&nbsp;&nbsp;&nbsp;铁扇子 &nbsp;&nbsp;&nbsp;&nbsp;宋　清';
character[77] = '　　地乐星 &nbsp;&nbsp;&nbsp;&nbsp;铁叫子 &nbsp;&nbsp;&nbsp;&nbsp;乐　和';
character[78] = '　　地捷星 &nbsp;&nbsp;&nbsp;&nbsp;花项虎 &nbsp;&nbsp;&nbsp;&nbsp;龚　旺';
character[79] = '　　地速星 &nbsp;&nbsp;&nbsp;&nbsp;中箭虎 &nbsp;&nbsp;&nbsp;&nbsp;丁得孙';
character[80] = '　　地镇星 &nbsp;&nbsp;&nbsp;&nbsp;小遮拦 &nbsp;&nbsp;&nbsp;&nbsp;穆　春';
character[81] = '　　地嵇星 &nbsp;&nbsp;&nbsp;&nbsp;操刀鬼 &nbsp;&nbsp;&nbsp;&nbsp;曹　正';
character[82] = '　　地魔星 &nbsp;&nbsp;&nbsp;&nbsp;云里金刚 &nbsp;&nbsp;&nbsp;&nbsp;宋　万';
character[83] = '　　地妖星 &nbsp;&nbsp;&nbsp;&nbsp;摸着天 &nbsp;&nbsp;&nbsp;&nbsp;杜　迁';
character[84] = '　　地幽星 &nbsp;&nbsp;&nbsp;&nbsp;病大虫 &nbsp;&nbsp;&nbsp;&nbsp;薛　永';
character[85] = '　　地伏星 &nbsp;&nbsp;&nbsp;&nbsp;金眼彪 &nbsp;&nbsp;&nbsp;&nbsp;施　恩';
character[86] = '　　地僻星 &nbsp;&nbsp;&nbsp;&nbsp;打虎将 &nbsp;&nbsp;&nbsp;&nbsp;李　忠';
character[87] = '　　地空星 &nbsp;&nbsp;&nbsp;&nbsp;小霸王 &nbsp;&nbsp;&nbsp;&nbsp;周　通';
character[88] = '　　地孤星 &nbsp;&nbsp;&nbsp;&nbsp;金钱豹子 &nbsp;&nbsp;&nbsp;&nbsp;汤　隆';
character[89] = '　　地全星 &nbsp;&nbsp;&nbsp;&nbsp;鬼脸儿 &nbsp;&nbsp;&nbsp;&nbsp;杜　兴';
character[90] = '　　地短星 &nbsp;&nbsp;&nbsp;&nbsp;出林龙 &nbsp;&nbsp;&nbsp;&nbsp;邹　渊';
character[91] = '　　地角星 &nbsp;&nbsp;&nbsp;&nbsp;独角龙 &nbsp;&nbsp;&nbsp;&nbsp;邹　润';
character[92] = '　　地囚星 &nbsp;&nbsp;&nbsp;&nbsp;旱地忽律 &nbsp;&nbsp;&nbsp;&nbsp;朱　贵';
character[93] = '　　地藏星 &nbsp;&nbsp;&nbsp;&nbsp;笑面虎 &nbsp;&nbsp;&nbsp;&nbsp;朱　富';
character[94] = '　　地平星 &nbsp;&nbsp;&nbsp;&nbsp;铁臂膊 &nbsp;&nbsp;&nbsp;&nbsp;蔡　福';
character[95] = '　　地损星 &nbsp;&nbsp;&nbsp;&nbsp;一枝花 &nbsp;&nbsp;&nbsp;&nbsp;蔡　庆';
character[96] = '　　地奴星 &nbsp;&nbsp;&nbsp;&nbsp;催命判官 &nbsp;&nbsp;&nbsp;&nbsp;李　立';
character[97] = '　　地察星 &nbsp;&nbsp;&nbsp;&nbsp;青眼虎 &nbsp;&nbsp;&nbsp;&nbsp;李　云';
character[98] = '　　地恶星 &nbsp;&nbsp;&nbsp;&nbsp;没面目 &nbsp;&nbsp;&nbsp;&nbsp;焦　挺';
character[99] = '　　地丑星 &nbsp;&nbsp;&nbsp;&nbsp;石将军 &nbsp;&nbsp;&nbsp;&nbsp;石　勇';
character[100] = '　　地数星 &nbsp;&nbsp;&nbsp;&nbsp;小尉迟 &nbsp;&nbsp;&nbsp;&nbsp;孙　新';
character[101] = '　　地阴星 &nbsp;&nbsp;&nbsp;&nbsp;母大虫 &nbsp;&nbsp;&nbsp;&nbsp;顾大嫂';sexflag[101] = 0;
character[102] = '　　地刑星 &nbsp;&nbsp;&nbsp;&nbsp;菜园子 &nbsp;&nbsp;&nbsp;&nbsp;张　青';
character[103] = '　　地壮星 &nbsp;&nbsp;&nbsp;&nbsp;母夜叉 &nbsp;&nbsp;&nbsp;&nbsp;孙二娘';sexflag[103] = 0;
character[104] = '　　地劣星 &nbsp;&nbsp;&nbsp;&nbsp;活闪婆 &nbsp;&nbsp;&nbsp;&nbsp;王定六';
character[105] = '　　地健星 &nbsp;&nbsp;&nbsp;&nbsp;险道神 &nbsp;&nbsp;&nbsp;&nbsp;郁保四';
character[106] = '　　地耗星 &nbsp;&nbsp;&nbsp;&nbsp;白日鼠 &nbsp;&nbsp;&nbsp;&nbsp;白　胜';
character[107] = '　　地贼星 &nbsp;&nbsp;&nbsp;&nbsp;鼓上蚤 &nbsp;&nbsp;&nbsp;&nbsp;时　迁';
character[108] = '　　地狗星 &nbsp;&nbsp;&nbsp;&nbsp;金毛犬 &nbsp;&nbsp;&nbsp;&nbsp;段景住';